@extends('admin.layouts.app', ['title'=>'Admissions Application'])
@section('content')
<section class="cm-page-head"><div><a class="cm-back-link" href="{{ route('admin.admissions.index') }}">&larr; Admissions Applications</a><span class="cm-eyebrow">{{ $application->reference_code }}</span><h1>{{ $application->student_name }}</h1><p>{{ $application->applying_for_level }} &middot; {{ $application->school_year }}</p></div></section>
@if(session('new_access_code'))<div class="cm-alert cm-alert--success"><strong>New private access code â€” copy now:</strong> {{ session('new_access_code') }}</div>@endif
<div class="p9c-admin-grid">
<section class="cm-panel"><div class="cm-panel__head"><div><span class="cm-eyebrow">Family</span><h2>Application details</h2></div></div><dl class="p9c-details"><div><dt>Guardian</dt><dd>{{ $application->guardian_name }}</dd></div><div><dt>Email</dt><dd>{{ $application->guardian_email ?: 'Not provided' }}</dd></div><div><dt>Phone</dt><dd>{{ $application->guardian_phone ?: 'Not provided' }}</dd></div><div><dt>Submitted</dt><dd>{{ $application->submitted_at?->format('M j, Y g:i A') }}</dd></div>@if($application->family_notes)<div><dt>Family notes</dt><dd>{{ $application->family_notes }}</dd></div>@endif</dl></section>
<section class="cm-panel"><div class="cm-panel__head"><div><span class="cm-eyebrow">Review</span><h2>Status and messages</h2></div></div><form method="POST" action="{{ route('admin.admissions.update',$application) }}" class="p9c-admin-form">@csrf @method('PATCH')<label>Status<select name="status" required>@foreach($statuses as $value=>$label)<option value="{{ $value }}" @selected($application->status===$value)>{{ $label }}</option>@endforeach</select></label><label>Family-visible message<textarea name="public_status_message" rows="5">{{ old('public_status_message',$application->public_status_message) }}</textarea></label><label>Private staff notes<textarea name="admin_notes" rows="5">{{ old('admin_notes',$application->admin_notes) }}</textarea></label><button class="cm-button cm-button--primary">Save review</button></form></section>
<section class="cm-panel cm-panel--wide p9c-span"><div class="cm-panel__head"><div><span class="cm-eyebrow">Private files</span><h2>Submitted documents</h2></div></div><div class="p9c-doc-list">@forelse($application->documents as $document)<article><div><strong>{{ $document->typeLabel() }}</strong><small>{{ $document->original_name }} &middot; {{ $document->formattedSize() }}</small></div><a href="{{ route('admin.admissions.documents.download',[$application,$document]) }}">Download</a><form method="POST" action="{{ route('admin.admissions.documents.verify',[$application,$document]) }}">@csrf @method('PATCH')<input type="hidden" name="is_verified" value="{{ $document->is_verified ? 0 : 1 }}"><input name="admin_notes" value="{{ $document->admin_notes }}" placeholder="Optional private note"><button class="cm-button cm-button--secondary">{{ $document->is_verified ? 'Remove verification' : 'Verify' }}</button></form></article>@empty<div class="cm-empty">No documents submitted.</div>@endforelse</div></section>
<section class="cm-panel"><div class="cm-panel__head"><div><span class="cm-eyebrow">Access</span><h2>Private tracking code</h2></div></div><p class="p9c-help">Rotate only after verifying the familyâ€™s request. The new code is displayed once.</p><form method="POST" action="{{ route('admin.admissions.rotate-access-code',$application) }}">@csrf<button class="cm-button cm-button--secondary">Generate new access code</button></form></section>
<section class="cm-panel"><div class="cm-panel__head"><div><span class="cm-eyebrow">History</span><h2>Admissions timeline</h2></div></div><div class="p9c-timeline">@forelse($application->events as $event)<article><strong>{{ str_replace('_',' ',$event->event_type) }}</strong><small>{{ $event->created_at->format('M j, Y g:i A') }}@if($event->actor) &middot; {{ $event->actor->name }}@endif</small>@if($event->public_message)<p>{{ $event->public_message }}</p>@endif</article>@empty<div class="cm-empty">No history.</div>@endforelse</div></section>
</div>
@endsection