@php($editing = isset($galleryItem))
@extends('admin.layouts.app', ['title' => $editing ? 'Edit Photo' : 'Upload Photo'])
@section('content')
<section class="cm-page-head"><div><a class="cm-back-link" href="{{ route('admin.gallery.index') }}">&larr; Photos</a><span class="cm-eyebrow">School gallery</span><h1>{{ $editing ? 'Edit Photo' : 'Upload Photo' }}</h1><p>Photo authorization and consent remain mandatory. Teachers submit photos for leadership review before publication.</p></div></section>
<form method="POST" enctype="multipart/form-data" action="{{ $editing ? route('admin.gallery.update',$galleryItem) : route('admin.gallery.store') }}" class="cm-compose">@csrf @if($editing) @method('PUT') @endif
@if($editing)<img src="{{ Storage::url($galleryItem->image_path) }}" alt="{{ $galleryItem->alt_text }}" class="cm-photo-preview">@endif
<label class="cm-field"><span>{{ $editing ? 'Replace Photo (optional)' : 'Photo' }}</span><input type="file" name="image" accept="image/jpeg,image/png,image/webp" {{ $editing ? '' : 'required' }}></label>
<div class="cm-two"><label class="cm-field"><span>Title</span><input name="title" required maxlength="180" value="{{ old('title',$galleryItem->title ?? '') }}"></label><label class="cm-field"><span>Category</span><input name="category" required maxlength="80" value="{{ old('category',$galleryItem->category ?? '') }}"></label></div>
<label class="cm-field"><span>Alt Text</span><input name="alt_text" required maxlength="250" value="{{ old('alt_text',$galleryItem->alt_text ?? '') }}"></label>
<label class="cm-field"><span>Caption</span><textarea name="caption" rows="4">{{ old('caption',$galleryItem->caption ?? '') }}</textarea></label>
<div class="cm-two"><label class="cm-field"><span>Date Taken</span><input type="date" name="taken_at" value="{{ old('taken_at',isset($galleryItem) && $galleryItem->taken_at ? $galleryItem->taken_at->format('Y-m-d'):'') }}"></label><label class="cm-field"><span>Photographer Credit</span><input name="photographer_credit" maxlength="180" value="{{ old('photographer_credit',$galleryItem->photographer_credit ?? '') }}"></label></div>
<input type="hidden" name="sort_order" value="{{ old('sort_order',$galleryItem->sort_order ?? 0) }}">
<div class="cm-consent-box"><label class="cm-check"><input type="checkbox" name="consent_confirmed" value="1" @checked(old('consent_confirmed',isset($galleryItem) && filled($galleryItem->consent_confirmed_at)))><span><strong>School authorization and appropriate consent are confirmed</strong></span></label>@if(!auth()->user()->isTeacher())<label class="cm-check"><input type="checkbox" name="is_published" value="1" @checked(old('is_published',isset($galleryItem) && $galleryItem->workflow_status==='published' && $galleryItem->is_published))><span><strong>Publish on Public Gallery</strong></span></label>@endif</div>
@if(isset($galleryItem) && $galleryItem->review_notes)<div class="cm-alert"><strong>Review note:</strong> {{ $galleryItem->review_notes }}</div>@endif
<div class="cm-compose-actions"><a class="cm-button cm-button--secondary" href="{{ route('admin.gallery.index') }}">Cancel</a>@if(auth()->user()->isTeacher())<button name="action" value="save" class="cm-button cm-button--secondary">Save Draft</button><button name="action" value="submit_review" class="cm-button cm-button--primary">Submit for Review</button>@else<button class="cm-button cm-button--primary">Save Photo</button>@endif</div>
</form>
@endsection
