<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
@page{size:A4 portrait;margin:13mm 14mm 15mm}
*{box-sizing:border-box}
body{font-family:"DejaVu Sans",sans-serif;font-size:10px;color:#17233c;margin:0}
.watermark{position:fixed;top:42%;left:5%;width:90%;text-align:center;font-size:48px;font-weight:700;color:#d7dde5;opacity:.34;z-index:-1}
.header{width:100%;border-collapse:collapse;border-bottom:2px solid #b89242;margin-bottom:14px}
.header td{padding:0 0 10px;vertical-align:middle}
.logo-cell{width:70px}.logo{width:58px;height:58px;object-fit:contain}
.school-name{font-size:17px;font-weight:700;color:#102a4c;margin:0}
.school-meta{font-size:8.5px;color:#556274;margin-top:3px}
.document-label{text-align:right;font-size:9px;font-weight:700;color:#8a6925}
.student{width:100%;border-collapse:collapse;margin-bottom:12px}
.student td{border:1px solid #d7dde5;padding:7px}.student small{display:block;color:#687386;margin-bottom:2px}
.grades{width:100%;border-collapse:collapse}.grades th,.grades td{border:1px solid #cfd7e0;padding:6px;text-align:center}
.grades th{background:#102a4c;color:#fff}.grades td:first-child{text-align:left;font-weight:700}
.attendance{width:100%;border-collapse:collapse;margin-top:12px}.attendance td{width:25%;border:1px solid #d7dde5;padding:7px;text-align:center}
.attendance strong{display:block;font-size:14px;color:#102a4c}
.signatures{width:100%;border-collapse:separate;border-spacing:24px 0;margin-top:42px}.signatures td{width:50%;border-top:1px solid #333;text-align:center;padding-top:5px;font-size:8.5px}
.note{margin-top:16px;font-size:7.8px;color:#667085;line-height:1.45}
</style>
</head>
<body>
<div class="watermark">{{ $branding['watermark'] }}</div>
<table class="header">
<tr>
<td class="logo-cell">@if($branding['logo_data_uri'])<img class="logo" src="{{ $branding['logo_data_uri'] }}" alt="">@endif</td>
<td>
    <p class="school-name">{{ $branding['school_name'] }}</p>
    <div class="school-meta">
        @if($branding['address']){{ $branding['address'] }}@endif
        @if($branding['phone']) · {{ $branding['phone'] }}@endif
        @if($branding['email']) · {{ $branding['email'] }}@endif
    </div>
</td>
<td class="document-label">STUDENT REPORT CARD<br>{{ $student->school_year }}</td>
</tr>
</table>

<table class="student">
<tr>
<td><small>Student</small><strong>{{ $student->fullName() }}</strong></td>
<td><small>Student No.</small><strong>{{ $student->student_number }}</strong></td>
<td><small>Grade / Section</small><strong>{{ $student->grade_level }}{{ $student->section ? ' · '.$student->section : '' }}</strong></td>
</tr>
</table>

<table class="grades">
<thead><tr><th>Subject</th><th>Q1</th><th>Q2</th><th>Q3</th><th>Q4</th><th>Final</th></tr></thead>
<tbody>
@forelse($record['subjects'] as $row)
<tr>
<td>{{ $row['subject'] }}</td>
@foreach(['Q1','Q2','Q3','Q4'] as $term)
<td>{{ $row['terms'][$term] !== null ? number_format($row['terms'][$term], 2) : '—' }}</td>
@endforeach
<td><strong>{{ $row['final'] !== null ? number_format($row['final'], 2) : '—' }}</strong></td>
</tr>
@empty
<tr><td colspan="6">No graded academic records are available yet.</td></tr>
@endforelse
</tbody>
</table>

<table class="attendance">
<tr>
<td><small>Present</small><strong>{{ $record['attendance']['present'] }}</strong></td>
<td><small>Absent</small><strong>{{ $record['attendance']['absent'] }}</strong></td>
<td><small>Late</small><strong>{{ $record['attendance']['late'] }}</strong></td>
<td><small>Excused</small><strong>{{ $record['attendance']['excused'] }}</strong></td>
</tr>
</table>

<table class="signatures"><tr><td>Class Adviser / Teacher</td><td>Principal / Authorized School Official</td></tr></table>
<p class="note">Static A4 PDF generated by NACS-Phil for {{ $generatedBy->name }} on {{ now()->format('M j, Y g:i A') }}. This PDF contains no editable form fields. School verification and authorized signatures remain controlling for official use.</p>
</body>
</html>
