<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
@page{size:A4 portrait;margin:13mm 14mm 15mm}
*{box-sizing:border-box}
body{font-family:"DejaVu Sans",sans-serif;font-size:10px;color:#17233c;margin:0}
.watermark{position:fixed;top:42%;left:5%;width:90%;text-align:center;font-size:46px;font-weight:700;color:#d7dde5;opacity:.34;z-index:-1}
.header{width:100%;border-collapse:collapse;border-bottom:2px solid #b89242;margin-bottom:14px}.header td{padding:0 0 10px;vertical-align:middle}
.logo-cell{width:70px}.logo{width:58px;height:58px;object-fit:contain}.school-name{font-size:17px;font-weight:700;color:#102a4c;margin:0}.school-meta{font-size:8.5px;color:#556274;margin-top:3px}
.document-label{text-align:right;font-size:9px;font-weight:700;color:#8a6925}
.status{margin:0 0 11px;padding:7px 9px;border:1px solid #d8b15a;background:#fff8e8;font-size:9px}
.student{width:100%;border-collapse:collapse;margin-bottom:12px}.student td{border:1px solid #d7dde5;padding:7px}.student small{display:block;color:#687386;margin-bottom:2px}
.year{margin-top:14px}.year-title{font-weight:700;font-size:11px;color:#102a4c;margin:0 0 5px}
.grades{width:100%;border-collapse:collapse}.grades th,.grades td{border:1px solid #cfd7e0;padding:6px}.grades th{background:#102a4c;color:#fff;text-align:left}.grades td:last-child{text-align:right;font-weight:700}
.signatures{width:100%;border-collapse:separate;border-spacing:24px 0;margin-top:42px}.signatures td{width:50%;border-top:1px solid #333;text-align:center;padding-top:5px;font-size:8.5px}
.note{margin-top:16px;font-size:7.8px;color:#667085;line-height:1.45}
</style>
</head>
<body>
<div class="watermark">{{ $branding['watermark'] }}</div>
<table class="header">
<tr>
<td class="logo-cell">@if($branding['logo_data_uri'])<img class="logo" src="{{ $branding['logo_data_uri'] }}" alt="">@endif</td>
<td>
    <p class="school-name">{{ $branding['school_name'] }}</p>
    <div class="school-meta">
        @if($branding['address']){{ $branding['address'] }}@endif
        @if($branding['phone']) · {{ $branding['phone'] }}@endif
        @if($branding['email']) · {{ $branding['email'] }}@endif
    </div>
</td>
<td class="document-label">TRANSCRIPT OF RECORDS<br>{{ $official ? 'OFFICIAL SCHOOL COPY' : 'DRAFT / UNOFFICIAL' }}</td>
</tr>
</table>

@if(!$official)
<div class="status"><strong>Draft / unofficial:</strong> an official TOR requires Principal / authorized school approval.</div>
@endif

<table class="student">
<tr>
<td><small>Student</small><strong>{{ $student->fullName() }}</strong></td>
<td><small>Student No.</small><strong>{{ $student->student_number }}</strong></td>
<td><small>Current Level</small><strong>{{ $student->grade_level }}</strong></td>
</tr>
</table>

@forelse($years as $year)
<section class="year">
<p class="year-title">School Year {{ $year['school_year'] }}</p>
<table class="grades">
<thead><tr><th>Subject</th><th>Final Grade</th></tr></thead>
<tbody>
@foreach($year['subjects'] as $subject)
<tr><td>{{ $subject['subject'] }}</td><td>{{ $subject['final'] !== null ? number_format($subject['final'], 2) : '—' }}</td></tr>
@endforeach
</tbody>
</table>
</section>
@empty
<p>No academic history is available yet.</p>
@endforelse

<table class="signatures"><tr><td>Prepared / Reviewed by</td><td>Principal / Authorized School Official</td></tr></table>
<p class="note">Static A4 PDF generated by NACS-Phil for {{ $generatedBy->name }} on {{ now()->format('M j, Y g:i A') }}. This PDF contains no editable form fields. Watermark and official/draft status are generated from the school system at export time.</p>
</body>
</html>
