<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Transcript - {{ $student->fullName() }}</title>
<style>
@page{size:A4 portrait;margin:12mm}
*{box-sizing:border-box}
body{font-family:Arial,Helvetica,sans-serif;margin:0;background:#eef2f6;color:#17233c}
.sheet{max-width:900px;margin:24px auto;background:#fff;border:1px solid #d7dde5;border-radius:16px;padding:28px;box-shadow:0 14px 40px rgba(23,35,60,.10)}
.head{display:grid;grid-template-columns:auto 1fr auto;gap:18px;align-items:center;border-bottom:3px solid #b89242;padding-bottom:18px}.logo{width:64px;height:64px;object-fit:contain}
.school h1{font-size:19px;margin:0}.school p{margin:4px 0 0;font-size:12px}.badge{font-size:11px;font-weight:700;padding:7px 10px;border:1px solid #b89242;border-radius:999px}
.student{display:grid;grid-template-columns:2fr 1fr 1fr;gap:12px;margin:20px 0}.meta{border:1px solid #e1e5eb;border-radius:10px;padding:10px}.meta small{display:block;color:#667085}.meta strong{display:block;margin-top:3px}
.year{margin-top:22px}.year h2{font-size:14px;margin:0 0 8px;color:#102a4c}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border:1px solid #d8dee7;padding:8px}th{background:#102a4c;color:#fff;text-align:left}td:last-child{text-align:right;font-weight:700}
.warning{padding:10px 12px;border:1px solid #d8b15a;background:#fff8e8;border-radius:9px;font-size:12px;margin:16px 0}
.signatures{display:grid;grid-template-columns:1fr 1fr;gap:70px;margin-top:54px}.line{border-top:1px solid #333;text-align:center;padding-top:6px;font-size:11px}
.note{margin-top:20px;font-size:11px;color:#667085}.actions{max-width:900px;margin:18px auto;display:flex;gap:10px}.actions button{padding:10px 15px;border:0;border-radius:9px;background:#102a4c;color:#fff;font-weight:700;cursor:pointer}
@media print{body{background:#fff}.sheet{margin:0;box-shadow:none;border:0;border-radius:0;padding:0}.actions{display:none}}
</style>
</head>
<body>
<div class="actions"><button type="button" onclick="window.print()">Print / Save as PDF</button></div>
<main class="sheet">
<header class="head">
<img class="logo" src="{{ \App\Models\SchoolSetting::logoUrl() }}" alt="">
<div class="school"><h1>Noel Academy Christian of Sariaya Philippines, Inc.</h1><p>Transcript of Records (TOR)</p></div>
<span class="badge">{{ $official ? 'OFFICIAL PRINT VIEW' : 'DRAFT / UNOFFICIAL' }}</span>
</header>
@if(!$official)
<div class="warning"><strong>Draft transcript.</strong> Teachers may generate this academic summary, but an official TOR requires Principal / authorized school approval.</div>
@endif
<section class="student">
<div class="meta"><small>Student</small><strong>{{ $student->fullName() }}</strong></div>
<div class="meta"><small>Student No.</small><strong>{{ $student->student_number }}</strong></div>
<div class="meta"><small>Current level</small><strong>{{ $student->grade_level }}</strong></div>
</section>
@forelse($years as $year)
<section class="year">
<h2>School Year {{ $year['school_year'] }}</h2>
<table><thead><tr><th>Subject</th><th>Final Grade</th></tr></thead><tbody>
@foreach($year['subjects'] as $subject)
<tr><td>{{ $subject['subject'] }}</td><td>{{ $subject['final'] !== null ? number_format($subject['final'], 2) : '—' }}</td></tr>
@endforeach
</tbody></table>
</section>
@empty
<p>No academic history is available yet.</p>
@endforelse
<div class="signatures"><div class="line">Prepared / Reviewed by</div><div class="line">Principal / Authorized School Official</div></div>
<p class="note">Generated by {{ $generatedBy->name }} on {{ now()->format('M j, Y g:i A') }}. The official status shown here is an authorization state for printing; future cryptographic/QR verification will be added before external electronic issuance.</p>
</main>
</body>
</html>
