@extends('layouts.public', ['title' => 'Contact'])
@section('content')
<section class="bg-nacs-900 py-20 text-white"><div class="page-shell"><p class="text-sm font-bold uppercase tracking-[.2em] text-gold-400">Contact and inquiry</p><h1 class="mt-4 max-w-4xl font-serif text-5xl font-bold">Connect with the NACS-Phil school office.</h1><p class="mt-6 max-w-3xl text-lg leading-8 text-emerald-100">Use this form for general questions and admissions interest only. Official contact details remain pending school verification.</p></div></section>
<section class="page-shell grid gap-10 py-20 lg:grid-cols-[.7fr_1.3fr]">
<aside class="rounded-2xl bg-nacs-50 p-7"><h2 class="font-serif text-2xl font-bold text-nacs-900">School information</h2><dl class="mt-6 grid gap-5 text-sm"><div><dt class="font-bold text-nacs-800">Address</dt><dd class="mt-1 leading-6 text-gray-600">{{ config('nacs.address') }}</dd></div><div><dt class="font-bold text-nacs-800">Phone</dt><dd class="mt-1 text-gray-600">{{ config('nacs.phone') ?: 'Pending official verification' }}</dd></div><div><dt class="font-bold text-nacs-800">Email</dt><dd class="mt-1 text-gray-600">{{ config('nacs.email') ?: 'Pending official verification' }}</dd></div><div><dt class="font-bold text-nacs-800">Facebook</dt><dd class="mt-1"><a href="{{ config('nacs.facebook_url') }}" target="_blank" rel="noopener noreferrer" class="font-bold text-nacs-700">Open official page</a></dd></div></dl></aside>
<div id="inquiry" class="rounded-2xl border border-gray-200 bg-white p-7 shadow-sm"><p class="eyebrow">Basic inquiry</p><h2 class="section-title mt-3 text-3xl">How may the school assist you?</h2>
@if($errors->any())<div class="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-900"><p class="font-bold">Please correct the following:</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('inquiries.store') }}" class="mt-7 grid gap-5 sm:grid-cols-2">@csrf
<div><label for="guardian_name" class="font-bold text-gray-800">Parent/guardian name</label><input id="guardian_name" name="guardian_name" value="{{ old('guardian_name') }}" required maxlength="100" class="focus-ring mt-2 w-full rounded-xl border border-gray-300 px-4 py-3"></div>
<div><label for="student_name" class="font-bold text-gray-800">Student name <span class="font-normal text-gray-500">(optional)</span></label><input id="student_name" name="student_name" value="{{ old('student_name') }}" maxlength="100" class="focus-ring mt-2 w-full rounded-xl border border-gray-300 px-4 py-3"></div>
<div><label for="email" class="font-bold text-gray-800">Email</label><input id="email" name="email" type="email" value="{{ old('email') }}" maxlength="150" class="focus-ring mt-2 w-full rounded-xl border border-gray-300 px-4 py-3"></div>
<div><label for="phone" class="font-bold text-gray-800">Phone</label><input id="phone" name="phone" value="{{ old('phone') }}" maxlength="40" class="focus-ring mt-2 w-full rounded-xl border border-gray-300 px-4 py-3"></div>
<div class="sm:col-span-2"><label for="level_interested" class="font-bold text-gray-800">Program of interest</label><select id="level_interested" name="level_interested" required class="focus-ring mt-2 w-full rounded-xl border border-gray-300 px-4 py-3"><option value="">Choose one</option>@foreach(['Preschool','Elementary','Junior High School','General Inquiry'] as $level)<option value="{{ $level }}" @selected(old('level_interested') === $level)>{{ $level }}</option>@endforeach</select></div>
<div class="sm:col-span-2"><label for="message" class="font-bold text-gray-800">Question or message</label><textarea id="message" name="message" rows="6" required maxlength="2000" class="focus-ring mt-2 w-full rounded-xl border border-gray-300 px-4 py-3">{{ old('message') }}</textarea></div>
<div class="hidden" aria-hidden="true"><label for="website">Website</label><input id="website" name="website" tabindex="-1" autocomplete="off"></div>
<label class="sm:col-span-2 flex items-start gap-3 rounded-xl bg-gray-50 p-4"><input type="checkbox" name="privacy_consent" value="1" required class="mt-1"><span class="text-sm leading-6 text-gray-700">I consent to the school using the information above to respond to this inquiry. I understand that I should not submit sensitive student documents through this form. Read the <a href="{{ route('privacy') }}" class="font-bold text-nacs-700">privacy notice</a>.</span></label>
<div class="sm:col-span-2"><button class="focus-ring rounded-xl bg-nacs-700 px-6 py-3 font-extrabold text-white hover:bg-nacs-800">Send inquiry</button></div>
</form></div></section>
@endsection
